services:
  api-nft-metadata:
    build: .
    container_name: nft-metadata
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-nft-metadata.rule=Host(`nft-metadata.brutusservices.com`)"
      - "traefik.http.routers.api-nft-metadata.entrypoints=websecure"
      - "traefik.http.routers.api-nft-metadata.tls.certresolver=myresolver"
      - "traefik.http.services.api-nft-metadata.loadbalancer.server.port=8000"

networks:
  web:
   external: true